export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAIL = 'FETCHING_POSTS_FAIL';

export const FETCHING_QUEUE = 'FETCHING_QUEUE';
export const FETCHING_QUEUE_SUCCESS = 'FETCHING_QUEUE_SUCCESS';
export const FETCHING_QUEUE_FAIL = 'FETCHING_QUEUE_FAIL';

export const FETCHING_QUEUE_ITEM = 'FETCHING_QUEUE_ITEM';
export const FETCHING_QUEUE_ITEM_SUCCESS = 'FETCHING_QUEUE_ITEM_SUCCESS';
export const FETCHING_QUEUE_ITEM_FAIL = 'FETCHING_QUEUE_ITEM_FAIL';

export const CREATING_QUEUE_ITEM = 'CREATING_QUEUE_ITEM';
export const CREATING_QUEUE_ITEM_SUCCESS = 'CREATING_QUEUE_ITEM_SUCCESS';
export const CREATING_QUEUE_ITEM_FAIL = 'CREATING_QUEUE_ITEM_FAIL';

export const UPDATING_QUEUE_ITEM = 'UPDATING_QUEUE_ITEM';
export const UPDATING_QUEUE_ITEM_SUCCESS = 'UPDATING_QUEUE_ITEM_SUCCESS';
export const UPDATING_QUEUE_ITEM_FAIL = 'UPDATING_QUEUE_ITEM_FAIL';

export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';

export const FETCHING_USERS = 'FETCHING_USERS';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_FAIL = 'FETCHING_USERS_FAIL';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAIL = 'FETCHING_USER_FAIL';

export const CREATING_USER = 'CREATING_USER';
export const CREATING_USER_SUCCESS = 'CREATING_USER_SUCCESS';
export const CREATING_USER_FAIL = 'CREATING_USER_FAIL';

export const UPDATING_USER = 'UPDATING_USER';
export const UPDATING_USER_SUCCESS = 'UPDATING_USER_SUCCESS';
export const UPDATING_USER_FAIL = 'UPDATING_USER_FAIL';

export const FETCHING_DISPATCHERS = 'FETCHING_DISPATCHERS';
export const FETCHING_DISPATCHERS_SUCCESS = 'FETCHING_DISPATCHERS_SUCCESS';
export const FETCHING_DISPATCHERS_FAIL = 'FETCHING_DISPATCHERS_FAIL';

export const FETCHING_DISPATCHER = 'FETCHING_DISPATCHER';
export const FETCHING_DISPATCHER_SUCCESS = 'FETCHING_DISPATCHER_SUCCESS';
export const FETCHING_DISPATCHER_FAIL = 'FETCHING_DISPATCHER_FAIL';

export const CREATING_DISPATCHER = 'CREATING_DISPATCHER';
export const CREATING_DISPATCHER_SUCCESS = 'CREATING_DISPATCHER_SUCCESS';
export const CREATING_DISPATCHER_FAIL = 'CREATING_DISPATCHER_FAIL';

export const UPDATING_DISPATCHER = 'UPDATING_DISPATCHER';
export const UPDATING_DISPATCHER_SUCCESS = 'UPDATING_DISPATCHER_SUCCESS';
export const UPDATING_DISPATCHER_FAIL = 'UPDATING_DISPATCHER_FAIL';

export const FETCHING_ADMINISTRATORS = 'FETCHING_ADMINISTRATORS';
export const FETCHING_ADMINISTRATORS_SUCCESS = 'FETCHING_ADMINISTRATORS_SUCCESS';
export const FETCHING_ADMINISTRATORS_FAIL = 'FETCHING_ADMINISTRATORS_FAIL';

export const FETCHING_ADMINISTRATOR = 'FETCHING_ADMINISTRATOR';
export const FETCHING_ADMINISTRATOR_SUCCESS = 'FETCHING_ADMINISTRATOR_SUCCESS';
export const FETCHING_ADMINISTRATOR_FAIL = 'FETCHING_ADMINISTRATOR_FAIL';

export const CREATING_ADMINISTRATOR = 'CREATING_ADMINISTRATOR';
export const CREATING_ADMINISTRATOR_SUCCESS = 'CREATING_ADMINISTRATOR_SUCCESS';
export const CREATING_ADMINISTRATOR_FAIL = 'CREATING_ADMINISTRATOR_FAIL';

export const UPDATING_ADMINISTRATOR = 'UPDATING_ADMINISTRATOR';
export const UPDATING_ADMINISTRATOR_SUCCESS = 'UPDATING_ADMINISTRATOR_SUCCESS';
export const UPDATING_ADMINISTRATOR_FAIL = 'UPDATING_ADMINISTRATOR_FAIL';
