export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAIL = 'FETCHING_POSTS_FAIL';

export const FETCHING_QUEUE = 'FETCHING_QUEUE';
export const FETCHING_QUEUE_SUCCESS = 'FETCHING_QUEUE_SUCCESS';
export const FETCHING_QUEUE_FAIL = 'FETCHING_QUEUE_FAIL';

export const FETCHING_QUEUE_ITEM = 'FETCHING_QUEUE_ITEM';
export const FETCHING_QUEUE_ITEM_SUCCESS = 'FETCHING_QUEUE_ITEM_SUCCESS';
export const FETCHING_QUEUE_ITEM_FAIL = 'FETCHING_QUEUE_ITEM_FAIL';

export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';

export const FETCHING_USERS = 'FETCHING_USERS';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_FAIL = 'FETCHING_USERS_FAIL';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAIL = 'FETCHING_USER_FAIL';

export const FETCHING_DISPATCHERS = 'FETCHING_DISPATCHERS';
export const FETCHING_DISPATCHERS_SUCCESS = 'FETCHING_DISPATCHERS_SUCCESS';
export const FETCHING_DISPATCHERS_FAIL = 'FETCHING_DISPATCHERS_FAIL';

export const FETCHING_DISPATCHER = 'FETCHING_DISPATCHER';
export const FETCHING_DISPATCHER_SUCCESS = 'FETCHING_DISPATCHER_SUCCESS';
export const FETCHING_DISPATCHER_FAIL = 'FETCHING_DISPATCHER_FAIL';

export const FETCHING_ADMINISTRATORS = 'FETCHING_ADMINISTRATORS';
export const FETCHING_ADMINISTRATORS_SUCCESS = 'FETCHING_ADMINISTRATORS_SUCCESS';
export const FETCHING_ADMINISTRATORS_FAIL = 'FETCHING_ADMINISTRATORS_FAIL';

export const FETCHING_ADMINISTRATOR = 'FETCHING_ADMINISTRATOR';
export const FETCHING_ADMINISTRATOR_SUCCESS = 'FETCHING_ADMINISTRATOR_SUCCESS';
export const FETCHING_ADMINISTRATOR_FAIL = 'FETCHING_ADMINISTRATOR_FAIL';
