export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAIL = 'FETCHING_POSTS_FAIL';

export const FETCHING_QUEUE = 'FETCHING_QUEUE';
export const FETCHING_QUEUE_SUCCESS = 'FETCHING_QUEUE_SUCCESS';
export const FETCHING_QUEUE_FAIL = 'FETCHING_QUEUE_FAIL';
